version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    environment:
      SA_PASSWORD: "@LiK|-|@nCh78ErL!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    
  todo-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5125:5125"
      - "7112:7112"
    volumes:
      - ./ToDo.App.Api/appsettings.json:/app/appsettings.json
      - ~/.aspnet/https:/https:ro
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:5125
      - ASPNETCORE_HTTPS_PORT=https://+:7112
      - ASPNETCORE_ENVIRONMENT=Development